### ISSUE TITLE
Autonomous play back doesnt work

### ISSUE THREAD

**Issue by rovaden** [Yeti-Robotics/olaf-java-2021#82]
when mapped to a button it runs correctly, but when inserted into the getAutoCommand, it stutters and stops.

**Comment by Yukigamine** [comment]
This is fixed, yes?

**Comment by rovaden** [comment]
not fixed but decided to just use button instead of autonomous running.
